version: '3.8'

services:
  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: Gateway.API/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - gateway-network
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_HTTPS_PORT=5001

  productos.api:
    image: ${DOCKER_REGISTRY-}productosapi
    build:
      context: ../../Microservicio-Producto/
      dockerfile: Productos.API/Dockerfile
    ports:
      - "5600:5600"
 
     
    networks:
      - gateway-network
    environment:
      - RABBIT_URL=amqps://xonggmoj:CrASQgnUWMJ_xBq2icgdoTz3h8snzbi-@kangaroo.rmq.cloudamqp.com/xonggmoj
      - RABBIT_USERNAME=xonggmoj
      - RABBIT_PASSWORD=CrASQgnUWMJ_xBq2icgdoTz3h8snzbi-
      - RABBIT_QUEUE=productos_queue
      - RABBIT_QUEUE_UPDATE=productosUpdate_queue
      - RABBIT_QUEUE_DELETE=productosdelete_queue
      - MONGODB_CNN_READ=mongodb+srv://aledance:1234@cluster0.y9o6cor.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - MONGODB_CNN_WRITE=mongodb+srv://aledance:1234@cluster0.y9o6cor.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - MONGODB_NAME_READ=product_read
      - MONGODB_NAME_WRITE=product_write
      - CLOUDINARY_URL=cloudinary://395359435159368:bdmFxshOSQseyDClGPzXqSRsAXE@mediaflows_5f35b392-be88-4e23-b142-ed6340d0d341
      - CLOUDINARY_CLOUD_NAME=mediaflows_5f35b392-be88-4e23-b142-ed6340d0d341
      - CLOUDINARY_API_KEY=395359435159368
      - CLOUDINARY_API_SECRET=bdmFxshOSQseyDClGPzXqSRsAXE
      - ASPNETCORE_URLS=http://+:5600
  puja.api:
    image: ${DOCKER_REGISTRY-}pujaapi
    build:
      context: ../../Microservicio-Pujas/Puja
      dockerfile: Puja.API/Dockerfile
    ports:
      - "5201:5201"
    networks:
      - gateway-network
    environment:
      - RABBIT_URL=amqps://xonggmoj:CrASQgnUWMJ_xBq2icgdoTz3h8snzbi-@kangaroo.rmq.cloudamqp.com/xonggmoj
      - RABBIT_USERNAME=xonggmoj
      - RABBIT_PASSWORD=CrASQgnUWMJ_xBq2icgdoTz3h8snzbi-
      - RABBIT_QUEUE=pujas_queue
      - RABBIT_QUEUE_UPDATE=pujasUpdate_queue
      - RABBIT_QUEUE_DELETE=pujasdelete_queue
      - MONGODB_CNN_READ=mongodb+srv://aledance:1234@cluster0.y9o6cor.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - MONGODB_CNN_WRITE=mongodb+srv://aledance:1234@cluster0.y9o6cor.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - MONGODB_NAME_READ=Puja_Read
      - MONGODB_NAME_WRITE=Puja_Write
      - ASPNETCORE_URLS=http://+:5201
      - SUBASTA_SERVICE_URL=http://subasta.api:5200
      

  subasta.api:
    image: ${DOCKER_REGISTRY-}subastaapi
    build:
      context: ../../MicroServicio_Subasta/Subasta.API
      dockerfile: Subasta.API/Dockerfile
    ports:
      - "5200:5200"
    networks:
      - gateway-network
    environment:
      - RABBIT_URL=amqps://xonggmoj:CrASQgnUWMJ_xBq2icgdoTz3h8snzbi-@kangaroo.rmq.cloudamqp.com/xonggmoj
      - RABBIT_USERNAME=xonggmoj
      - RABBIT_PASSWORD=CrASQgnUWMJ_xBq2icgdoTz3h8snzbi-
      - RABBIT_QUEUE=subasta_queue
      - RABBIT_QUEUE_UPDATE=update-subasta-queue
      - RABBIT_QUEUE_DELETE=delete-subasta-queue
      - ASPNETCORE_URLS=http://+:5200
      - MONGODB_CNN_READ=mongodb+srv://aledance:1234@cluster0.y9o6cor.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - MONGODB_CNN_WRITE=mongodb+srv://aledance:1234@cluster0.y9o6cor.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - MONGODB_NAME_READ=subasta_read
      - MONGODB_NAME_WRITE=subasta_write
  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: ../../Microservicio-Usuario/Users.API
      dockerfile: Users.API/Dockerfile
    ports:
      - "5103:5103"
    networks:
      - gateway-network
    environment:
      - RABBIT_URL=amqps://xonggmoj:CrASQgnUWMJ_xBq2icgdoTz3h8snzbi-@kangaroo.rmq.cloudamqp.com/xonggmoj
      - RABBIT_USERNAME=xonggmoj
      - RABBIT_PASSWORD=CrASQgnUWMJ_xBq2icgdoTz3h8snzbi-
      - RABBIT_QUEUE=Users_queue
      - RABBIT_QUEUE_UPDATE=UsersUpdate_queue
      - RABBIT_QUEUE_DELETE=UsersDelete_queue
      - ASPNETCORE_URLS=http://+:5103
      - MONGODB_CNN_READ=mongodb+srv://aledance:1234@cluster0.y9o6cor.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - MONGODB_CNN_WRITE=mongodb+srv://aledance:1234@cluster0.y9o6cor.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - MONGODB_NAME_READ=User_read
      - MONGODB_NAME_WRITE=User_write
      - CONFIRMATION_BASE_URL=http://localhost:3000
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=master
      - KEYCLOAK_CLIENT_ID=Usersclient
      - KEYCLOAK_CLIENT_SECRET=riHoCg1rAKIcd8loDdLIqMcR3DzexaDZ
    
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - gateway-network
  
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
    command: start-dev
    networks:
      - gateway-network
    volumes:
      - ./themes:/opt/keycloak/themes

networks:
  gateway-network:
    driver: bridge